#!/usr/bin/with-contenv sh

## remove current node
REMOTES=$(echo $REMOTES | sed -r "s/( )?${HKKN}( )?/\1\2/")
## remove duplicates
REMOTES=$(echo $REMOTES | xargs -n1 | sort -u | xargs)
## build remotes string
RMT_STR=""
for N in $REMOTES; do
    RMT_STR="$RMT_STR 127.0.0.${N}:${REMOTE_PORT}:127.0.0.${N}:${REMOTE_PORT} "
done

exec chisel client $ROUTER $RMT_STR