#!/usr/bin/with-contenv sh

if [ -e /etc/runtime.d ]; then
    for s in /etc/runtime.d/*; do
        svcName="$(basename $s)"
        svcPath="/etc/services.d/$svcName"
        mkdir -p "$svcPath"
        cp -pLf "$s" "$svcPath/run"
        chmod +x "$svcPath/run" 2>/dev/null
    done
fi
