#!/bin/sh

if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME:-/home/default}:/bin/sh" >> /etc/passwd
    mkdir -p ${HOME:-/home/default}
  fi
fi
