#!/bin/sh

rm -rf /run/postgresql/*
rm -rf /tmp/.s*

#mkdir -p $PGDATA
#pg_ctl initdb -D $PGDATA -U $(whoami)
#pg_ctl start -D $PGDATA -s -w -t $PGSTARTTIMEOUT
#createdb $(whoami)

#psql -c "CREATE EXTENSION citus;"
/usr/local/bin/create_ext.sh & disown

. /usr/share/postgresql-common/init.d-functions

## start postgres_cluster
echo $PORT
ver=$(ls /etc/postgresql/ | head -1)
clu=$(ls /etc/postgresql/$ver/ | head -1)
exec pg_ctlcluster $ver $clu start -foreground
