#!/bin/sh

rm -rf /run/postgresql/*
rm -rf /tmp/.s*

## create cluster config
. /etc/.pg
pg_createcluster --createclusterconf=/etc/postgresql-common/createcluster.conf $ver $clu
pg_conftool $ver $clu set shared_preload_libraries citus
pg_conftool $ver $clu set listen_addresses '*'
cp /etc/pg_hba.conf /etc/postgresql/${ver}/${clu}/pg_hba.conf

nohup /usr/local/bin/create_ext.sh &>/dev/null &

. /usr/share/postgresql-common/init.d-functions

## start postgres_cluster
exec pg_ctlcluster $ver $clu start -foreground
